#!/bin/bash

cd "$(dirname "$0")"

SCALA_VERSION=2.10
JAVA_OPTS=-Xmx4g
VERSION=0.1-SNAPSHOT

if [ ! -e target/scala-$SCALA_VERSION/gwn-scala-api-assembly-$VERSION.jar ]
then
    sbt assembly
fi

java -jar target/scala-$SCALA_VERSION/gwn-scala-api-assembly-$VERSION.jar $@
