#!/bin/bash

GWN_HOME="$(dirname "$0")"

SCALA_VERSION=2.10
JAVA_OPTS=-Xmx4g
VERSION=0.1-SNAPSHOT

if [ ! -e $GWN_HOME/target/scala-$SCALA_VERSION/gwn-scala-api-assembly-$VERSION.jar ]
then
    cd $GWN_HOME
    sbt assembly
    cd -
fi

java -jar $GWN_HOME/target/scala-$SCALA_VERSION/gwn-scala-api-assembly-$VERSION.jar "$@"
